#!/bin/bash

echo "📋 Comandos para executar manualmente no Shell:"
echo ""
echo "# Remover lock do Git (se necessário)"
echo "rm -f .git/index.lock"
echo ""
echo "# Adicionar arquivos limpos"
echo "git add .gitignore"
echo "git add *.py"
echo "git add templates/"
echo "git add scripts/"
echo "git add README.md replit.md"
echo ""
echo "# Commit com limpeza"
echo "git commit -m 'Limpeza: removidos arquivos grandes, otimizado .gitignore'"
echo ""
echo "# Push para GitHub (mantém link VPS)"
echo "git push"
echo ""
echo "✅ Resultado esperado:"
echo "- Arquivos grandes removidos do projeto atual"
echo "- .gitignore configurado para evitar futuros problemas"
echo "- Link com VPS mantido"
echo "- Histórico Git permanece (172MB no pack)"
echo ""
echo "ℹ️ O histórico de 172MB será naturalmente reduzido com o tempo"
echo "   conforme novos commits sobrescreverem o histórico antigo."